# See all available variables at https://nvuillam.github.io/mega-linter/configuration/ and in linters documentation.

# Config
APPLY_FIXES: all
DEFAULT_BRANCH: master
FILEIO_REPORTER: false
IGNORE_GITIGNORED_FILES: true
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true

JAVASCRIPT_DEFAULT_STYLE: prettier
JAVASCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .js
  - .jsx
TYPESCRIPT_DEFAULT_STYLE: prettier
TYPESCRIPT_PRETTIER_FILE_EXTENSIONS:
  - .ts
  - .tsx

  # Commands
PRE_COMMANDS:
  - command: npm install
    cwd: root

# Linters
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - SPELL_CSPELL
  - SPELL_MISSPELL
