[tool.poetry]
name = "api-editor"
version = "0.1.0"
description = ""
authors = ["GideonKoenig <ginosiassa.koenig@online.de>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
