name: 'Bug report'
description: 'Report that something does not work as expected'
labels: ['bug :beetle:']

body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (optional)
      description: Do you have anything else to add?
    validations:
      required: false
