name: 'Feature request'
description: 'Suggest an idea for this project'
labels: ['enhancement :bulb:']

body:
  - type: textarea
    id: related-problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "Example: I'm always frustrated when [...]"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Desired solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Possible alternatives (optional)
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (optional)
      description: Do you have anything else to add?
    validations:
      required: false
