name: 'Missing annotation (autogen)'
description: "An annotation should have been generated automatically but wasn't."
labels: ['bug :beetle:', 'missing annotation']

body:
  - type: input
    id: url-hash
    attributes:
      label: URL Hash
      description: Copy the part of the URL that starts with `#` from the address bar of your browser.
      placeholder: 'ex. #/sklearn/sklearn.metrics'
    validations:
      required: true

  - type: dropdown
    id: expected-annotation-type
    attributes:
      label: Expected Annotation Type
      description: Which annotation did you expect to be generated automatically?
      options:
        - '`@boundary`'
        - '`@enum`'
        - '`@remove`'
        - '`@value`'
    validations:
      required: true

  - type: textarea
    id: expected-annotation-inputs
    attributes:
      label: Expected Annotation Inputs
      description: Which inputs did you expect the annotation to have? If possible, provide the JSON for the expected annotation.
    validations:
      required: true

  - type: textarea
    id: minimal-api-data
    attributes:
      label: Minimal API Data (optional)
      description: If possible, provide the JSON for a minimal API with the element that should have been annotated, and its ancestors.
    validations:
      required: false

  - type: textarea
    id: minimal-usage-store
    attributes:
      label: Minimal Usage Store (optional)
      description: If possible, provide the JSON for a minimal usage store with the element that should have been annotated, and its ancestors.
    validations:
      required: false

  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested Solution (optional)
      description: Do you already have an idea how this problem could be fixed?
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (optional)
      description: Do you have anything else to add?
    validations:
      required: false
