import { IconButton, Tooltip } from '@chakra-ui/react';
import React from 'react';
import { FaFlag } from 'react-icons/fa';
import { missingAnnotationURL } from '../externalLinks/urlBuilder';
import { useAppSelector } from '../../app/hooks';
import { selectComplete, selectUsernameIsValid } from './annotationSlice';
import { selectRawPythonPackage } from '../packageData/apiSlice';
import { selectUsages } from '../usages/usageSlice';

interface MissingAnnotationButtonProps {
    target: string;
}

export const MissingAnnotationButton: React.FC<MissingAnnotationButtonProps> = function ({ target }) {
    const isComplete = Boolean(useAppSelector(selectComplete(target)));
    const isValidUsername = Boolean(useAppSelector(selectUsernameIsValid));
    const isDisabled = isComplete || !isValidUsername;

    const pythonPackage = useAppSelector(selectRawPythonPackage);
    const usages = useAppSelector(selectUsages);

    return (
        <Tooltip label="Report missing autogenerated annotation">
            <IconButton
                icon={<FaFlag />}
                aria-label="Report Missing Annotation"
                size="sm"
                variant="outline"
                colorScheme="orange"
                disabled={isDisabled}
                onClick={() => {
                    window.open(missingAnnotationURL(target, pythonPackage, usages), '_blank');
                }}
            />
        </Tooltip>
    );
};
