import { IconButton, Tooltip, useToast } from '@chakra-ui/react';
import React from 'react';
import { FaFlag } from 'react-icons/fa';
import { useAppSelector } from '../../app/hooks';
import { selectComplete, selectUsernameIsValid } from './annotationSlice';

interface MissingAnnotationButtonProps {
    target: string;
}

export const MissingAnnotationButton: React.FC<MissingAnnotationButtonProps> = function ({ target }) {
    const isComplete = Boolean(useAppSelector(selectComplete(target)));
    const isValidUsername = Boolean(useAppSelector(selectUsernameIsValid));
    const isDisabled = isComplete || !isValidUsername;
    const toast = useToast()

    return (
        <Tooltip label="Report a missing autogenerated annotation.">
            <IconButton
                icon={<FaFlag />}
                aria-label="Report Missing Annotation"
                size="sm"
                variant="outline"
                colorScheme="orange"
                disabled={isDisabled}
                onClick={() => {
                    toast({
                        colorScheme: "blue",
                        description: "Removed for double-blind review."
                    })
                }}
            />
        </Tooltip>
    );
};
