import { IconButton, Tooltip } from '@chakra-ui/react';
import React from 'react';
import { FaFlag } from 'react-icons/fa';
import { missingAnnotationURL } from '../externalLinks/urlBuilder';

interface MissingAnnotationButtonProps {
    target: string;
}

export const MissingAnnotationButton: React.FC<MissingAnnotationButtonProps> = function ({ target }) {
    return (
        <Tooltip label="Report missing autogenerated annotation">
            <IconButton
                icon={<FaFlag />}
                aria-label="Report Missing Annotation"
                size="sm"
                variant="outline"
                colorScheme="orange"
                onClick={() => {
                    window.open(missingAnnotationURL(target), '_blank');
                }}
            />
        </Tooltip>
    );
};
