package com.larsreimann.apiEditor.features.annotations.model

import com.larsreimann.apiEditor.features.ast.model.PythonDeclarationId
import com.larsreimann.apiEditor.features.users.model.Bots
import kotlinx.serialization.Serializable

@Serializable
sealed class Annotation {

    /**
     * The ID of the targeted declaration.
     */
    abstract val target: PythonDeclarationId<*>

    /**
     * A list of changes made to this annotation.
     */
    abstract val changelog: List<AnnotationChange>

    /**
     * The result of reviewing this annotation or `null` if it has not been reviewed yet.
     */
    abstract val review: AnnotationReview?

    /**
     * Returns whether this annotation is autogenerated. If the author is not known, we assume the annotation was
     * created manually.
     */
    fun isAutogenerated() = changelog.firstOrNull()?.author == Bots.Autogen

    /**
     * Returns whether someone has reviewed this annotation.
     */
    fun isReviewed() = review != null
}
