package com.larsreimann.apiEditor.features.users.model

@JvmInline
value class Username(private val value: String) {
    override fun toString(): String = value
}

fun String.asUsername(): Username = Username(this)

/**
 * Usernames of various bots in this program.
 */
object Bots {

    /**
     * The author of autogenerated annotations.
     */
    val Autogen = Username("\$autogen\$")
}
