name: Pull Request

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-api-editor:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api-editor

    strategy:
      matrix:
        node-version: [ 16.x ]
        java-version: [ 17 ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: api-editor/gui/package-lock.json

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: gradle

      # See https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle
      - name: Setup Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: ./gradlew check koverMergedHtmlReport

      - name: Upload test report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: backend test report
          path: api-editor/backend/build/reports
          if-no-files-found: ignore

      - name: Upload test coverage
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/upload-artifact@v3
        with:
          name: backend test coverage
          path: api-editor/build/reports/kover/html/

  gui-test-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api-editor/gui

    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: api-editor/gui/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test with Jest
        run: npm run test-with-coverage

      - name: Upload test report
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/upload-artifact@v3
        with:
          name: gui test coverage
          path: api-editor/gui/coverage/lcov-report

  build-package-parser:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./package-parser
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3.0.5
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install library
        run: poetry install --no-interaction

      - name: Smoke test (api)
        run: poetry run parse-package api -p package_parser -s package_parser -o out

      - name: Smoke test (usages)
        run: poetry run parse-package usages -p package_parser -c package_parser -o out

      - name: Smoke test (annotations)
        run: poetry run parse-package annotations -a tests/data/removeAnnotations/api_data.json -u tests/data/removeAnnotations/usage_data.json -o out/annotations.json

      - name: Smoke test (all)
        run: poetry run parse-package all -p package_parser -s package_parser -c package_parser -o out

      # Requires installation of pytest and pytest-cov
      - name: Test with pytest
        run: poetry run pytest --doctest-modules --cov=package_parser --cov-report=html

      - name: Upload test coverage
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: actions/upload-artifact@v3
        with:
          name: package-parser test coverage
          path: package-parser/htmlcov
