name: Pull Request

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.head_ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-api-editor:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api-editor

    strategy:
      matrix:
        node-version: [ 18.x ]
        java-version: [ 17 ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: api-editor/gui/package-lock.json

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}
          cache: gradle

      # See https://docs.github.com/en/actions/guides/building-and-testing-java-with-gradle
      - name: Setup Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Build with Gradle
        run: ./gradlew build koverMergedXmlReport

      - name: Upload test report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: backend test report
          path: api-editor/backend/build/reports
          if-no-files-found: ignore

      - name: Upload coverage to Codecov
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: api-editor/build/reports/kover/merged/xml
          files: report.xml

  gui-test-coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api-editor/gui

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: api-editor/gui/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test with Vitest
        run: npm run test-with-coverage

      - name: Upload coverage to Codecov
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: api-editor/gui/coverage
          files: coverage-final.json
